name: Run Prisma Migrations

on:
  push:
    branches: [ main ]

concurrency:
  group: 'prisma-migrate'
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run Prisma migrations
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          npx prisma migrate deploy --schema=prisma/schema.prisma
          npx prisma db seed --schema=prisma/schema.prisma || true
